SELECT table_name FROM user_tables;

SELECT * FROM PRODUCT_CATEGORIES

SELECT * FROM PRODUCTS

SELECT * FROM PRODUCTS_X_CATEGORY

SELECT * FROM CUSTOMERS WHERE customer_id = 96;

SELECT * FROM ORDERS WHERE CUSTOMER_ID = 96;

SELECT sequence_name FROM user_sequences ORDER BY 1;

UPDATE app.ORDERS 
SET CITY = 'Dabas'
WHERE customer_id = 96;

SELECT product_name,category_name FROM app.PRODUCTS p 
INNER JOIN app.PRODUCTS_X_CATEGORY pxc  ON p.ITEM_ID = pxc.ITEM_ID 
INNER JOIN app.PRODUCT_CATEGORIES pc ON pc.CATEGORY_ID = pxc.CATEGORY_ID 