FROM python:3.12-slim AS builder

WORKDIR /app

COPY requirements.consumer.txt .

RUN python -m venv /app/venv && \
    /app/venv/bin/pip install --upgrade pip --no-cache-dir && \
    /app/venv/bin/pip install --no-cache-dir -r requirements.consumer.txt

FROM python:3.12-slim AS runtime

WORKDIR /app

COPY --from=builder /app/venv /app/venv
COPY producer/ ./producer/

ENV PATH="/app/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

CMD ["python", "producer/error_simulator.py"]
