{
  "type": "record",
  "name": "Customer",
  "namespace": "app",
  "fields": [
    {"name": "CUSTOMER_ID", "type": "long"},
    {"name": "FIRST_NAME",  "type": "string"},
    {"name": "LAST_NAME",   "type": "string"},
    {"name": "EMAIL",       "type": "string"},
    {"name": "MOBILE",      "type": ["null", "string"], "default": null},
    {"name": "CITY",        "type": ["null", "string"], "default": null},
    {"name": "COUNTRY",     "type": ["null", "string"], "default": null},
    {"name": "CREATED_AT",  "type": "long", "logicalType": "timestamp-micros"},
    {"name": "CREATED_BY",  "type": "string"},
    {"name": "MODIFIED_AT", "type": ["null", "long"],   "default": null, "logicalType": "timestamp-micros"},
    {"name": "MODIFIED_BY", "type": ["null", "string"], "default": null}
  ]
}
